name: Feature request
description: Propose an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What problem does this solve?
    validations:
      required: true
